name: task_intern_3_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  bloc: ^8.1.3
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_secure_storage: ^9.0.0
  flutter_session_manager: ^1.0.3
  jwt_decoder: ^2.0.1
  localstorage: ^4.0.1+4
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
